name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Build Variant
        run: echo "BUILD_VARIANT=${{ inputs.build_variant || 'treble_arm64_bgN' }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io python3-pip unzip xz-utils
          pip3 install docker-compose

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f build/Dockerfile -t ponces/treble .

      - name: Build ROM
        run: |
          mkdir -p builds
          docker run --rm \
                     --privileged \
                     --name treble-build \
                     --volume ${{ runner.temp }}/.ssh:/root/.ssh \
                     --volume ${{ github.workspace }}/builds:/root/builds \
                     ponces/treble treblebuild ${{ env.BUILD_VARIANT }}

      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_VARIANT }}
          path: builds/*.xz
